#!/usr/bin/env bash
cd ~

if test -z "$XDG_RUNTIME_DIR"; then
    export XDG_RUNTIME_DIR=$(mktemp -d /tmp/$(id -u)-runtime-dir.XXX)
fi

if [ -f /etc/arch-release ]; then
	#
elif [ -f /etc/gentoo-release ]; then
	doas rc-service wpa_supplicant start
fi

$(ssh-agent -s)

# export WLR_NO_HARDWARE_CURSOTS="1"

# exec dbus-launch --exit-with-session Hyprland
exec dbus-run-session Hyprland
