require("plugins/lazydev")
require("plugins/conform")
require("plugins/oil")
require("plugins/fzf")
require("plugins/harpoon")
require("plugins/blink")
require("plugins/copilot")
require("plugins/vimwiki")
