require("plugins/tmux-navigation")
require("plugins/lazydev")
require("plugins/conform")
require("plugins/oil")
require("plugins/fzf")
require("plugins/blink")
require("plugins/copilot")
require("plugins/vimwiki")
-- require("plugins/fff")
require("plugins/treesitter")
require("plugins/comment")
